
#!/bin/bash
set -e
##################################################################################################################
# Author 	: 	Abdiasriver
# Website 	: 	https://www.axeso.red
##################################################################################################################
#
pacaur -S alsa-firmware --noconfirm --needed
pacaur -S alsa-lib --noconfirm --needed
pacaur -S alsa-plugins  --noconfirm --needed
pacaur -S arandr --noconfirm --needed
pacaur -S arch-install-scripts --noconfirm --needed
pacaur -S archlabs-common --noconfirm --needed
pacaur -S archlabs-downgrade --noconfirm --needed
pacaur -S archlabs-fonts --noconfirm --needed
pacaur -S archlabs-greeter --noconfirm --needed
pacaur -S archlabs-homepage --noconfirm --needed
pacaur -S archlabs-icons --noconfirm --needed
pacaur -S archlabs-jgmenu --noconfirm --needed
pacaur -S archlabs-keyring --noconfirm --needed
pacaur -S archlabs-kickshaw --noconfirm --needed
pacaur -S archlabs-neofetch --noconfirm --needed
pacaur -S archlabs-networkmanager-dmenu --noconfirm --needed
pacaur -S archlabs-ob-autostart --noconfirm --needed
pacaur -S archlabs-obkey --noconfirm --needed
pacaur -S archlabs-oblogout --noconfirm --needed
pacaur -S archlabs-opensnap --noconfirm --needed
pacaur -S archlabs-pacli --noconfirm --needed
pacaur -S archlabs-paranoid --noconfirm --needed
pacaur -S archlabs-pipemenus --noconfirm --needed
pacaur -S archlabs-polybar --noconfirm --needed
pacaur -S archlabs-rofi --noconfirm --needed
pacaur -S archlabs-screenlock --noconfirm --needed
pacaur -S archlabs-skippy-xd --noconfirm --needed
pacaur -S archlabs-themes --noconfirm --needed
pacaur -S archlabs-user-skel --noconfirm --needed
pacaur -S archlabs-wallpapers --noconfirm --needed
pacaur -S archlabs-yaourt --noconfirm --needed
pacaur -S audacious --noconfirm --needed
pacaur -S autoconf --noconfirm --needed
pacaur -S automake --noconfirm --needed
pacaur -S b43-fwcutter --noconfirm --needed
pacaur -S bash --noconfirm --needed
pacaur -S bind-tools --noconfirm --needed
pacaur -S binutils --noconfirm --needed
pacaur -S bison --noconfirm --needed
pacaur -S btrfs-progs --noconfirm --needed
pacaur -S bzip2 --noconfirm --needed
pacaur -S chromium-widevine --noconfirm --needed
pacaur -S clonezilla --noconfirm --needed
pacaur -S clutter-gtk --noconfirm --needed
pacaur -S compton --noconfirm --needed
pacaur -S conky --noconfirm --needed
pacaur -S coreutils --noconfirm --needed
pacaur -S crda --noconfirm --needed
pacaur -S cryptsetup --noconfirm --needed
pacaur -S darkhttpd --noconfirm --needed
pacaur -S ddrescue --noconfirm --needed
pacaur -S device-mapper --noconfirm --needed
pacaur -S dhclient --noconfirm --needed
pacaur -S dhcpcd --noconfirm --needed
pacaur -S dialog --noconfirm --needed
pacaur -S diffutils --noconfirm --needed
pacaur -S dmidecode --noconfirm --needed
pacaur -S dmraid --noconfirm --needed
pacaur -S dnsmasq --noconfirm --needed
pacaur -S dosfstools --noconfirm --needed
pacaur -S dunst --noconfirm --needed
pacaur -S e2fsprogs --noconfirm --needed
pacaur -S efitools --noconfirm --needed
pacaur -S ethtool --noconfirm --needed
pacaur -S exfat-utils --noconfirm --needed
pacaur -S f2fs-tools --noconfirm --needed
pacaur -S fakeroot --noconfirm --needed
pacaur -S ffmpeg2.8 --noconfirm --needed
pacaur -S file --noconfirm --needed
pacaur -S file-roller --noconfirm --needed
pacaur -S filesystem --noconfirm --needed
pacaur -S findutils --noconfirm --needed
pacaur -S firefox --noconfirm --needed
pacaur -S fsarchiver --noconfirm --needed
pacaur -S galculator --noconfirm --needed
pacaur -S gawk --noconfirm --needed
pacaur -S gcc --noconfirm --needed
pacaur -S gcc-libs --noconfirm --needed
pacaur -S geany --noconfirm --needed
pacaur -S gettext --noconfirm --needed
pacaur -S git --noconfirm --needed
pacaur -S glibc --noconfirm --needed
pacaur -S gnome-disk-utility --noconfirm --needed
pacaur -S gnome-keyring --noconfirm --needed
pacaur -S gnu-netcat --noconfirm --needed
pacaur -S gparted --noconfirm --needed
pacaur -S gpicview --noconfirm --needed
pacaur -S gpm --noconfirm --needed
pacaur -S gptfdisk --noconfirm --needed
pacaur -S grep --noconfirm --needed
pacaur -S grml-zsh-config --noconfirm --needed
pacaur -S grub --noconfirm --needed
pacaur -S gsimplecal --noconfirm --needed
pacaur -S gst-libav --noconfirm --needed
pacaur -S gst-plugins-base --noconfirm --needed
pacaur -S gst-plugins-good --noconfirm --needed
pacaur -S gstreamer --noconfirm --needed
pacaur -S gtk-engine-murrine --noconfirm --needed
pacaur -S gtk-engines --noconfirm --needed
pacaur -S gvfs --noconfirm --needed
pacaur -S gvfs-afc --noconfirm --needed
pacaur -S gvfs-mtp --noconfirm --needed
pacaur -S gvfs-nfs --noconfirm --needed
pacaur -S vim --noconfirm --needed
pacaur -S gzip --noconfirm --needed
pacaur -S haveged --noconfirm --needed
pacaur -S hdparm --noconfirm --needed
pacaur -S htop --noconfirm --needed
pacaur -S imagemagick --noconfirm --needed
pacaur -S inetutils --noconfirm --needed
pacaur -S intel-ucode --noconfirm --needed
pacaur -S iproute2 --noconfirm --needed
pacaur -S iputils --noconfirm --needed
pacaur -S ipw2100-fw --noconfirm --needed
pacaur -S ipw2200-fw --noconfirm --needed
pacaur -S irssi --noconfirm --needed
pacaur -S jfsutils --noconfirm --needed
pacaur -S jsoncpp --noconfirm --needed
pacaur -S less --noconfirm --needed
pacaur -S lftp --noconfirm --needed
pacaur -S libgee --noconfirm --needed
pacaur -S libmad --noconfirm --needed
pacaur -S libmatroska --noconfirm --needed
pacaur -S libmpdclient --noconfirm --needed
pacaur -S licenses --noconfirm --needed
pacaur -S lightdm --noconfirm --needed
pacaur -S linux-atm --noconfirm --needed
pacaur -S linux-lts --noconfirm --needed
pacaur -S lm_sensors --noconfirm --needed
pacaur -S logrotate --noconfirm --needed
pacaur -S lsb-release --noconfirm --needed
pacaur -S lsscsi --noconfirm --needed
pacaur -S lvm2 --noconfirm --needed
pacaur -S lxappearance --noconfirm --needed
pacaur -S lxappearance-obconf --noconfirm --needed
pacaur -S lxsession --noconfirm --needed
pacaur -S make --noconfirm --needed
pacaur -S man-db --noconfirm --needed
pacaur -S man-pages --noconfirm --needed
pacaur -S mdadm --noconfirm --needed
pacaur -S memtest86+ --noconfirm --needed
pacaur -S mesa --noconfirm --needed
pacaur -S mkinitcpio-nfs-utils --noconfirm --needed
pacaur -S mkinitcpio-openswap --noconfirm --needed
pacaur -S mtools --noconfirm --needed
pacaur -S nano --noconfirm --needed
pacaur -S nbd --noconfirm --needed
pacaur -S ndisc6 --noconfirm --needed
pacaur -S netctl --noconfirm --needed
pacaur -S networkmanager --noconfirm --needed
pacaur -S networkmanager-dispatcher-ntpd
pacaur -S nfs-utils --noconfirm --needed
pacaur -S nilfs-utils --noconfirm --needed
pacaur -S nitrogen --noconfirm --needed
pacaur -S nmap --noconfirm --needed
pacaur -S ntp --noconfirm --needed
pacaur -S numlockx --noconfirm --needed
pacaur -S obconf --noconfirm --needed
pacaur -S openbox --noconfirm --needed
pacaur -S openconnect --noconfirm --needed
pacaur -S openshot --noconfirm --needed
pacaur -S openssh --noconfirm --needed
pacaur -S openvpn --noconfirm --needed
pacaur -S os-prober --noconfirm --needed
pacaur -S p7zip --noconfirm --needed
pacaur -S pacman --noconfirm --needed
pacaur -S pamixer --noconfirm --needed
pacaur -S partclone --noconfirm --needed
pacaur -S parted --noconfirm --needed
pacaur -S partimage --noconfirm --needed
pacaur -S patch --noconfirm --needed
pacaur -S pavucontrol --noconfirm --needed
pacaur -S pciutils --noconfirm --needed
pacaur -S pcmciautils --noconfirm --needed
pacaur -S perl --noconfirm --needed
pacaur -S pkg-config --noconfirm --needed
pacaur -S plank --noconfirm --needed
pacaur -S playerctl --noconfirm --needed
pacaur -S polkit --noconfirm --needed
pacaur -S ppp --noconfirm --needed
pacaur -S pptpclient --noconfirm --needed
pacaur -S procps-ng --noconfirm --needed
pacaur -S psmisc --noconfirm --needed
pacaur -S pulseaudio --noconfirm --needed
pacaur -S pulseaudio-alsa --noconfirm --needed
pacaur -S python2-xdg --noconfirm --needed
pacaur -S qt4 --noconfirm --needed
pacaur -S ranger --noconfirm --needed
pacaur -S refind-efi --noconfirm --needed
pacaur -S reflector --noconfirm --needed
pacaur -S reiserfsprogs --noconfirm --needed
pacaur -S rp-pppoe --noconfirm --needed
pacaur -S rsync --noconfirm --needed
pacaur -S s-nail --noconfirm --needed
pacaur -S scrot --noconfirm --needed
pacaur -S sdparm --noconfirm --needed
pacaur -S sed --noconfirm --needed
pacaur -S sg3_utils --noconfirm --needed
pacaur -S shadow --noconfirm --needed
pacaur -S simplescreenrecorder --noconfirm --needed
pacaur -S smartmontools --noconfirm --needed
pacaur -S speedtouch --noconfirm --needed
pacaur -S sudo --noconfirm --needed
pacaur -S sysfsutils --noconfirm --needed
pacaur -S syslinux --noconfirm --needed
pacaur -S systemd-sysvcompat --noconfirm --needed
pacaur -S tar --noconfirm --needed
pacaur -S tcpdump --noconfirm --needed
pacaur -S termite --noconfirm --needed
pacaur -S testdisk --noconfirm --needed
pacaur -S texinfo --noconfirm --needed
pacaur -S thunar --noconfirm --needed
pacaur -S tint2 --noconfirm --needed
pacaur -S trayer --noconfirm --needed
pacaur -S ttf-freefont --noconfirm --needed
pacaur -S ttf-liberation --noconfirm --needed
pacaur -S ttf-roboto --noconfirm --needed
pacaur -S ttf-ubuntu-font-family --noconfirm --needed
pacaur -S tumbler --noconfirm --needed
pacaur -S unrar --noconfirm --needed
pacaur -S usb_modeswitch --noconfirm --needed
pacaur -S usbutils --noconfirm --needed
pacaur -S util-linux --noconfirm --needed
pacaur -S vi --noconfirm --needed
pacaur -S vlc --noconfirm --needed
pacaur -S volumeicon --noconfirm --needed
pacaur -S vpnc --noconfirm --needed
pacaur -S wpm --noconfirm --needed
pacaur -S wget --noconfirm --needed
pacaur -S which --noconfirm --needed
pacaur -S wipe --noconfirm --needed
pacaur -S wireless-regdb --noconfirm --needed
pacaur -S wireless_tools --noconfirm --needed
pacaur -S wmctrl --noconfirm --needed
pacaur -S wpa_actiond --noconfirm --needed
pacaur -S wpa_supplicant --noconfirm --needed
pacaur -S wvdial --noconfirm --needed
pacaur -S xdg-user-dirs-gtk --noconfirm --needed
pacaur -S xdotool --noconfirm --needed
pacaur -S xf86-input-evdev --noconfirm --needed
pacaur -S xf86-input-keyboard --noconfirm --needed
pacaur -S xf86-input-libinput --noconfirm --needed
pacaur -S xf86-input-mouse --noconfirm --needed
pacaur -S xf86-input-synaptics --noconfirm --needed
pacaur -S xf86-input-vmmouse --noconfirm --needed
pacaur -S xf86-input-void --noconfirm --needed
pacaur -S xf86-video-amdgpu --noconfirm --needed
pacaur -S xf86-video-ati --noconfirm --needed
pacaur -S xf86-video-dummy --noconfirm --needed
pacaur -S xf86-video-fbdev --noconfirm --needed
pacaur -S xf86-video-intel --noconfirm --needed
pacaur -S xf86-video-nouveau --noconfirm --needed
pacaur -S xf86-video-openchrome --noconfirm --needed
pacaur -S xf86-video-qxl --noconfirm --needed
pacaur -S xf86-video-vesa --noconfirm --needed
pacaur -S xf86-video-vmware --noconfirm --needed
pacaur -S xf86-video-voodoo --noconfirm --needed
pacaur -S xfce4-settings --noconfirm --needed
pacaur -S xfsprogs --noconfirm --needed
pacaur -S xl2tpd --noconfirm --needed
pacaur -S xorg-bdftopcf --noconfirm --needed
pacaur -S xorg-iceauth --noconfirm --needed
pacaur -S xorg-luit --noconfirm --needed
pacaur -S xorg-mkfontdir --noconfirm --needed
pacaur -S xorg-mkfontscale --noconfirm --needed
pacaur -S xorg-server --noconfirm --needed
pacaur -S xorg-sessreg --noconfirm --needed
pacaur -S xorg-setxkbmap --noconfirm --needed
pacaur -S xorg-smproxy --noconfirm --needed
pacaur -S xorg-x11perf --noconfirm --needed
pacaur -S xorg-xauth --noconfirm --needed
pacaur -S xorg-xbacklight --noconfirm --needed
pacaur -S xorg-xcmsdb --noconfirm --needed
pacaur -S xorg-xcursorgen --noconfirm --needed
pacaur -S xorg-xdpyinfo --noconfirm --needed
pacaur -S xorg-xdriinfo --noconfirm --needed
pacaur -S xorg-xev --noconfirm --needed
pacaur -S xorg-xgamma --noconfirm --needed
pacaur -S xorg-xhost --noconfirm --needed
pacaur -S xorg-xinit --noconfirm --needed
pacaur -S xorg-xinput --noconfirm --needed
pacaur -S xorg-xkbcomp --noconfirm --needed
pacaur -S xorg-xkbevd --noconfirm --needed
pacaur -S xorg-xkbutils --noconfirm --needed
pacaur -S xorg-xkill --noconfirm --needed
pacaur -S xorg-xlsatoms --noconfirm --needed
pacaur -S xorg-xlsclients --noconfirm --needed
pacaur -S xorg-xmodmap --noconfirm --needed
pacaur -S xorg-xpr --noconfirm --needed
pacaur -S xorg-xprop --noconfirm --needed
pacaur -S xorg-xrandr --noconfirm --needed
pacaur -S xorg-xrdb --noconfirm --needed
pacaur -S xorg-xrefresh --noconfirm --needed
pacaur -S xorg-xset --noconfirm --needed
pacaur -S xorg-xsetroot --noconfirm --needed
pacaur -S xorg-xvinfo --noconfirm --needed
pacaur -S xorg-xwd --noconfirm --needed
pacaur -S xorg-xwininfo --noconfirm --needed
pacaur -S xorg-xwud --noconfirm --needed
pacaur -S zd1211-firmware --noconfirm --needed
pacaur -S zenity --noconfirm --needed
pacaur -S zsh --noconfirm --needed

##################################################################################################################
#                                    TERMINADO
# Website 	: 	https://www.axeso.red
##################################################################################################################

#
