
#!/bin/bash
set -e
##################################################################################################################
# Author 	: 	Abdiasriver
# Website 	: 	https://www.axeso.red
##################################################################################################################
#
pacaur -S alsa-firmware
pacaur -S alsa-lib
pacaur -S alsa-plugins
pacaur -S arandr
pacaur -S arch-install-scripts
pacaur -S archlabs-common
pacaur -S archlabs-downgrade
pacaur -S archlabs-fonts
pacaur -S archlabs-greeter
pacaur -S archlabs-homepage
pacaur -S archlabs-icons
pacaur -S archlabs-jgmenu
pacaur -S archlabs-keyring
pacaur -S archlabs-kickshaw
pacaur -S archlabs-neofetch
pacaur -S archlabs-networkmanager-dmenu
pacaur -S archlabs-ob-autostart
pacaur -S archlabs-obkey
pacaur -S archlabs-oblogout
pacaur -S archlabs-opensnap
pacaur -S archlabs-pacli
pacaur -S archlabs-paranoid
pacaur -S archlabs-pipemenus
pacaur -S archlabs-polybar
pacaur -S archlabs-rofi
pacaur -S archlabs-screenlock
pacaur -S archlabs-skippy-xd
pacaur -S archlabs-themes
pacaur -S archlabs-user-skel
pacaur -S archlabs-wallpapers
pacaur -S archlabs-yaourt
pacaur -S audacious
pacaur -S autoconf
pacaur -S automake
pacaur -S b4pacaur -S -fwcutter
pacaur -S bash
pacaur -S bind-tools
pacaur -S binutils
pacaur -S bison
pacaur -S btrfs-progs
pacaur -S bzip2
pacaur -S chromium-widevine
pacaur -S clonezilla
pacaur -S clutter-gtk
pacaur -S compton
pacaur -S conky
pacaur -S coreutils
pacaur -S crda
pacaur -S cryptsetup
pacaur -S darkhttpd
pacaur -S ddrescue
pacaur -S device-mapper
pacaur -S dhclient
pacaur -S dhcpcd
pacaur -S dialog
pacaur -S diffutils
pacaur -S dmidecode
pacaur -S dmraid
pacaur -S dnsmasq
pacaur -S dosfstools
pacaur -S dunst
pacaur -S e2fsprogs
pacaur -S efitools
pacaur -S ethtool
pacaur -S exfat-utils
pacaur -S f2fs-tools
pacaur -S fakeroot
pacaur -S ffmpeg2.8
pacaur -S file
pacaur -S file-roller
pacaur -S filesystem
pacaur -S findutils
pacaur -S firefox
pacaur -S fsarchiver
pacaur -S galculator
pacaur -S gawk
pacaur -S gcc
pacaur -S gcc-libs
pacaur -S geany
pacaur -S gettext
pacaur -S git
pacaur -S gksu
pacaur -S glibc
pacaur -S gnome-disk-utility
pacaur -S gnome-keyring
pacaur -S gnu-netcat
pacaur -S gparted
pacaur -S gpicview
pacaur -S gpm
pacaur -S gptfdisk
pacaur -S grep
pacaur -S grml-zsh-config
pacaur -S grub
pacaur -S gsimplecal
pacaur -S gst-libav
pacaur -S gst-plugins-base
pacaur -S gst-plugins-good
pacaur -S gstreamer
pacaur -S gtk-engine-murrine
pacaur -S gtk-engines
pacaur -S gvfs
pacaur -S gvfs-afc
pacaur -S gvfs-mtp
pacaur -S gvfs-nfs
pacaur -S vim
pacaur -S gzip
pacaur -S haveged
pacaur -S hdparm
pacaur -S htop
pacaur -S imagemagick
pacaur -S inetutils
pacaur -S intel-ucode
pacaur -S iproute2
pacaur -S iputils
pacaur -S ipw2100-fw
pacaur -S ipw2200-fw
pacaur -S irssi
pacaur -S jfsutils
pacaur -S jsoncpp
pacaur -S less
pacaur -S lftp
pacaur -S libgee
pacaur -S libmad
pacaur -S libmatroska
pacaur -S libmpdclient
pacaur -S licenses
pacaur -S lightdm
pacaur -S linux-atm
pacaur -S linux-lts
pacaur -S lm_sensors
pacaur -S logrotate
pacaur -S lsb-release
pacaur -S lsscsi
pacaur -S lvm2
pacaur -S lxappearance
pacaur -S lxappearance-obconf
pacaur -S lxsession
pacaur -S make
pacaur -S man-db
pacaur -S man-pages
pacaur -S mdadm
pacaur -S memtest86+
pacaur -S mesa
pacaur -S mkinitcpio-nfs-utils
pacaur -S mkinitcpio-openswap
pacaur -S mtools
pacaur -S nano
pacaur -S nbd
pacaur -S ndisc6
pacaur -S netctl
pacaur -S networkmanager
pacaur -S networkmanager-dispatcher-ntpd
pacaur -S nfs-utils
pacaur -S nilfs-utils
pacaur -S nitrogen
pacaur -S nmap
pacaur -S ntfs-pacaur -S g
pacaur -S ntp
pacaur -S numlockx
pacaur -S obconf
pacaur -S openbox
pacaur -S openconnect
pacaur -S openshot
pacaur -S openssh
pacaur -S openvpn
pacaur -S os-prober
pacaur -S p7zip
pacaur -S pacman
pacaur -S pamixer
pacaur -S partclone
pacaur -S parted
pacaur -S partimage
pacaur -S patch
pacaur -S pavucontrol
pacaur -S pciutils
pacaur -S pcmciautils
pacaur -S perl
pacaur -S pkg-config
pacaur -S plank
pacaur -S playerctl
pacaur -S polkit
pacaur -S ppp
pacaur -S pptpclient
pacaur -S procps-ng
pacaur -S psmisc
pacaur -S pulseaudio
pacaur -S pulseaudio-alsa
pacaur -S python2-xdg
pacaur -S qt4
pacaur -S ranger
pacaur -S refind-efi
pacaur -S reflector
pacaur -S reiserfsprogs
pacaur -S rp-pppoe
pacaur -S rsync
pacaur -S s-nail
pacaur -S scrot
pacaur -S sdparm
pacaur -S sed
pacaur -S sg3_utils
pacaur -S shadow
pacaur -S simplescreenrecorder
pacaur -S smartmontools
pacaur -S speedtouch
pacaur -S sudo
pacaur -S sysfsutils
pacaur -S syslinux
pacaur -S systemd-sysvcompat
pacaur -S tar
pacaur -S tcpdump
pacaur -S termite
pacaur -S testdisk
pacaur -S texinfo
pacaur -S thunar
pacaur -S tint2
pacaur -S trayer
pacaur -S ttf-freefont
pacaur -S ttf-liberation
pacaur -S ttf-roboto
pacaur -S ttf-ubuntu-font-family
pacaur -S tumbler
pacaur -S unrar
pacaur -S usb_modeswitch
pacaur -S usbutils
pacaur -S util-linux
pacaur -S vi
pacaur -S vlc
pacaur -S volumeicon
pacaur -S vpnc
pacaur -S wpacaur -S m
pacaur -S wget
pacaur -S which
pacaur -S wipe
pacaur -S wireless-regdb
pacaur -S wireless_tools
pacaur -S wmctrl
pacaur -S wpa_actiond
pacaur -S wpa_supplicant
pacaur -S wvdial
pacaur -S xdg-user-dirs-gtk
pacaur -S xdotool
pacaur -S xf86-input-evdev
pacaur -S xf86-input-keyboard
pacaur -S xf86-input-libinput
pacaur -S xf86-input-mouse
pacaur -S xf86-input-synaptics
pacaur -S xf86-input-vmmouse
pacaur -S xf86-input-void
pacaur -S xf86-video-amdgpu
pacaur -S xf86-video-ati
pacaur -S xf86-video-dummy
pacaur -S xf86-video-fbdev
pacaur -S xf86-video-intel
pacaur -S xf86-video-nouveau
pacaur -S xf86-video-openchrome
pacaur -S xf86-video-qxl
pacaur -S xf86-video-vesa
pacaur -S xf86-video-vmware
pacaur -S xf86-video-voodoo
pacaur -S xfce4-settings
pacaur -S xfsprogs
pacaur -S xl2tpd
pacaur -S xorg-bdftopcf
pacaur -S xorg-iceauth
pacaur -S xorg-luit
pacaur -S xorg-mkfontdir
pacaur -S xorg-mkfontscale
pacaur -S xorg-server
pacaur -S xorg-sessreg
pacaur -S xorg-setxkbmap
pacaur -S xorg-smproxy
pacaur -S xorg-x11perf
pacaur -S xorg-xauth
pacaur -S xorg-xbacklight
pacaur -S xorg-xcmsdb
pacaur -S xorg-xcursorgen
pacaur -S xorg-xdpyinfo
pacaur -S xorg-xdriinfo
pacaur -S xorg-xev
pacaur -S xorg-xgamma
pacaur -S xorg-xhost
pacaur -S xorg-xinit
pacaur -S xorg-xinput
pacaur -S xorg-xkbcomp
pacaur -S xorg-xkbevd
pacaur -S xorg-xkbutils
pacaur -S xorg-xkill
pacaur -S xorg-xlsatoms
pacaur -S xorg-xlsclients
pacaur -S xorg-xmodmap
pacaur -S xorg-xpr
pacaur -S xorg-xprop
pacaur -S xorg-xrandr
pacaur -S xorg-xrdb
pacaur -S xorg-xrefresh
pacaur -S xorg-xset
pacaur -S xorg-xsetroot
pacaur -S xorg-xvinfo
pacaur -S xorg-xwd
pacaur -S xorg-xwininfo
pacaur -S xorg-xwud
pacaur -S zd1211-firmware
pacaur -S zenity
pacaur -S zsh

##################################################################################################################
#                                    TERMINADO
# Website 	: 	https://www.axeso.red
##################################################################################################################

#
